num1 = input("input num1 :")
num2 = input("input num2 :")
num3 = input("input num3 :")
num4 = input("input num4 :")
num5 = input("input num5 :")
print('complex of 1 Equal',complex(num1))
print('float of 2 Equal',float(num2))
print('complex of 2 Equal',complex(num2))
print('float of 3 Equal',float(num3))
print('complex of 3 Equal',complex(num3))
print('float of 4 Equal',float(num4))
print('complex of 4 Equal',complex(num4))
print('float of 5 Equal',float(num5))
print('complex of 5 Equal',complex(num5))