print("Day Converter Program -->")
day = int(input("Input number of days:"))
print(day ,"Days -->Hour",day*24,"Hours" )
print(day ,"Days -->Minutes",day*60*24,"Minutes" )
print(day ,"Days -->Seconds",day*60*60*24 ,"Seconds")
